name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "servidor"
          username: "usuari"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /ruta/al/projecte
            git pull origin main
            npm install --production
            pm2 restart aplicacio
